# 服务端口
server:
  port: 81

spring:
  application:
    name: service-gateway # 服务名
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # 使用服务发现路由
      routes:
        - id: service-hosp # 设置路由id
          uri: lb://service-hosp # 设置路由uri
          predicates: #设置路由断言
            - name: Path
              args:
                - /*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - name: Path
              args:
                - /*/cmn/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - name: Path
              args:
                - /*/user/**
                - /*/ucenter/**
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - name: Path
              args:
                - /*/msm/**